version: '2'
services:
  myapp:
    image: jupyter:scipy-notebook
    user: 'jovyan'
    build: .
    volumes:
      - .:/home/jovyan/work
    environment:
      # Adjust to your screen size
      - DISPLAY_WIDTH=1366
      - DISPLAY_HEIGHT=768
      - RUN_XTERM=no
    cap_add:
      - NET_ADMIN
    devices:
    - "/dev/net/tun:/dev/net/tun"
    - /dev/null:/dev/null
    privileged: true
    ports:
      - "8888:8888"
    networks:
      - x11
networks:
  x11:
